
services:

  mysql:
    image: mysql:8.0.40-debian
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: gvendas
      MYSQL_PASSWORD: gvendas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gvendas_db

  jaeger:
    image: jaegertracing/all-in-one:1.39
    container_name: jaeger
    ports: #localhost:4317 para protocolo grpc, localhost:4318 protocolo http
      - 4317:4317 # GRPC server
      - 4318:4318 # HTTP server
      #- 5778:5778 # jaeger-agent HTTP server
      #- 14250:14250 # jaeger-collector gRPC server
      #- 14268:14268 # jaeger-collector HTTP server
      #- 16685:16685 # GRPC server
      - 16686:16686 # Jaeger UI -  HTTP server      
    environment:
      COLLECTOR_OTLP_ENABLED: true